version: 2
models:
  - name: bronze__care_site
    config:
      alias: CARE_SITE
      schema: bronze
    tests: []
  - name: bronze__cdm_source
    config:
      alias: CDM_SOURCE
      schema: bronze
    tests: []
  - name: bronze__cohort_definition
    config:
      alias: COHORT_DEFINITION
      schema: bronze
    tests: []
  - name: bronze__cohort
    config:
      alias: COHORT
      schema: bronze
    tests: []
  - name: bronze__concept_ancestor
    config:
      alias: CONCEPT_ANCESTOR
      schema: bronze
    tests: []
  - name: bronze__concept_class
    config:
      alias: CONCEPT_CLASS
      schema: bronze
    tests: []
  - name: bronze__concept_relationship
    config:
      alias: CONCEPT_RELATIONSHIP
      schema: bronze
    tests: []
  - name: bronze__concept_synonym
    config:
      alias: CONCEPT_SYNONYM
      schema: bronze
    tests: []
  - name: bronze__concept
    config:
      alias: CONCEPT
      schema: bronze
    tests: []
  - name: bronze__condition_era
    config:
      alias: CONDITION_ERA
      schema: bronze
    tests: []
  - name: bronze__condition_occurrence
    config:
      alias: CONDITION_OCCURRENCE
      schema: bronze
    tests: []
  - name: bronze__cost
    config:
      alias: COST
      schema: bronze
    tests: []
  - name: bronze__death
    config:
      alias: DEATH
      schema: bronze
    tests: []
  - name: bronze__device_exposure
    config:
      alias: DEVICE_EXPOSURE
      schema: bronze
    tests: []
  - name: bronze__domain
    config:
      alias: DOMAIN
      schema: bronze
    tests: []
  - name: bronze__dose_era
    config:
      alias: DOSE_ERA
      schema: bronze
    tests: []
  - name: bronze__drug_era
    config:
      alias: DRUG_ERA
      schema: bronze
    tests: []
  - name: bronze__drug_exposure
    config:
      alias: DRUG_EXPOSURE
      schema: bronze
    tests: []
  - name: bronze__drug_strength
    config:
      alias: DRUG_STRENGTH
      schema: bronze
    tests: []
  - name: bronze__episode_event
    config:
      alias: EPISODE_EVENT
      schema: bronze
    tests: []
  - name: bronze__episode
    config:
      alias: EPISODE
      schema: bronze
    tests: []
  - name: bronze__fact_relationship
    config:
      alias: FACT_RELATIONSHIP
      schema: bronze
    tests: []
  - name: bronze__location
    config:
      alias: LOCATION
      schema: bronze
    tests: []
  - name: bronze__measurement
    config:
      alias: MEASUREMENT
      schema: bronze
    tests: []
  - name: bronze__metadata
    config:
      alias: METADATA
      schema: bronze
    tests: []
  - name: bronze__note_nlp
    config:
      alias: NOTE_NLP
      schema: bronze
    tests: []
  - name: bronze__note
    config:
      alias: NOTE
      schema: bronze
    tests: []
  - name: bronze__observation_period
    config:
      alias: OBSERVATION_PERIOD
      schema: bronze
    tests: []
  - name: bronze__observation
    config:
      alias: OBSERVATION
      schema: bronze
    tests: []
  - name: bronze__payer_plan_period
    config:
      alias: PAYER_PLAN_PERIOD
      schema: bronze
    tests: []
  - name: bronze__person
    config:
      alias: PERSON
      schema: bronze
    tests: []
  - name: bronze__procedure_occurrence
    config:
      alias: PROCEDURE_OCCURRENCE
      schema: bronze
    tests: []
  - name: bronze__provider
    config:
      alias: PROVIDER
      schema: bronze
    tests: []
  - name: bronze__relationship
    config:
      alias: RELATIONSHIP
      schema: bronze
    tests: []
  - name: bronze__source_to_concept_map
    config:
      alias: SOURCE_TO_CONCEPT_MAP
      schema: bronze
    tests: []
  - name: bronze__specimen
    config:
      alias: SPECIMEN
      schema: bronze
    tests: []
  - name: bronze__visit_detail
    config:
      alias: VISIT_DETAIL
      schema: bronze
    tests: []
  - name: bronze__visit_occurrence
    config:
      alias: VISIT_OCCURRENCE
      schema: bronze
    tests: []
  - name: bronze__vocabulary
    config:
      alias: VOCABULARY
      schema: bronze
    tests: []
